# Manual brand/model mapping for Mode Expert.
# Mode Expert only checks brand + model (no year/generation/trim), so several catalog
# entries intentionally share the same (brand, model) pair -- that's by design, per the
# user's rule that precise version/year should not be required.
BRAND_MODEL = {
    "Peugeot 208 (Mk2)": ("Peugeot", "208"),
    "Fiat 500L Cross": ("Fiat", "500L"),
    "Mazda MX-5": ("Mazda", "MX-5"),
    "Volvo 245": ("Volvo", "245"),
    "Skoda Favorit": ("Skoda", "Favorit"),
    "Hyundai Veloster": ("Hyundai", "Veloster"),
    "Chevrolet Corvette": ("Chevrolet", "Corvette"),
    "Mini (classique)": ("Mini", "Mini"),
    "Jeep Wrangler": ("Jeep", "Wrangler"),
    "Kia Sorento": ("Kia", "Sorento"),
    "Land Rover Defender": ("Land Rover", "Defender"),
    "Jeep Grand Cherokee": ("Jeep", "Grand Cherokee"),
    "Renault 4": ("Renault", "4"),
    "Renault Clio": ("Renault", "Clio"),
    "Peugeot 208 GTi": ("Peugeot", "208"),
    "Porsche 911": ("Porsche", "911"),
    "Ford Mustang": ("Ford", "Mustang"),
    "Ford Mustang (1968)": ("Ford", "Mustang"),
    "Ford Edge": ("Ford", "Edge"),
    "Citroën C2": ("Citroen", "C2"),
    "BMW X6 M": ("BMW", "X6"),
    "BMW 323i (E21)": ("BMW", "323i"),
    "Nissan Ariya": ("Nissan", "Ariya"),
    "Fiat 500 (1967)": ("Fiat", "500"),
    "Audi A4": ("Audi", "A4"),
    "Fiat Punto": ("Fiat", "Punto"),
    "Honda Civic": ("Honda", "Civic"),
    "Mercedes-Benz SL (R107)": ("Mercedes-Benz", "SL"),
    "Alfa Romeo Giulia": ("Alfa Romeo", "Giulia"),
    "BMW 320d Touring": ("BMW", "Serie 3"),
    "Dacia Duster": ("Dacia", "Duster"),
    "Porsche 911 Turbo S": ("Porsche", "911"),
    "Toyota RAV4": ("Toyota", "RAV4"),
    "Fiat Panda": ("Fiat", "Panda"),
    "BMW 2000 (classique)": ("BMW", "2000"),
    "Volkswagen Golf (2008)": ("Volkswagen", "Golf"),
    "Toyota Corolla": ("Toyota", "Corolla"),
    "Toyota Yaris": ("Toyota", "Yaris"),
    "Audi TT": ("Audi", "TT"),
    "Ford Ranger": ("Ford", "Ranger"),
    "Mercedes-Benz Classe E": ("Mercedes-Benz", "Classe E"),
    "Volkswagen Phaeton": ("Volkswagen", "Phaeton"),
    "Honda HR-V": ("Honda", "HR-V"),
    "Alfa Romeo Giulia Quadrifoglio": ("Alfa Romeo", "Giulia"),
    "Fiat 500L": ("Fiat", "500L"),
    "Fiat 500e": ("Fiat", "500"),
    "Ferrari FF": ("Ferrari", "FF"),
    "Toyota Land Cruiser": ("Toyota", "Land Cruiser"),
    "Lexus GS-F": ("Lexus", "GS"),
    "Peugeot 2008 II": ("Peugeot", "2008"),
    "Opel Corsa": ("Opel", "Corsa"),
    "Renault Captur": ("Renault", "Captur"),
    "Citroën C4 III": ("Citroen", "C4"),
    "Volkswagen Polo": ("Volkswagen", "Polo"),
    "Skoda Octavia": ("Skoda", "Octavia"),
    "Renault Mégane IV": ("Renault", "Megane"),
    "Peugeot 3008 II": ("Peugeot", "3008"),
    "Seat Ibiza": ("Seat", "Ibiza"),
    "Renault Twingo III": ("Renault", "Twingo"),
    "Dacia Sandero": ("Dacia", "Sandero"),
    "Nissan Qashqai": ("Nissan", "Qashqai"),
    "Renault Mégane": ("Renault", "Megane"),
    "Mercedes-Benz 560 SEL (W126)": ("Mercedes-Benz", "Classe S"),
    "Mercedes-Benz Classe C": ("Mercedes-Benz", "Classe C"),
    "Citroën C3 III": ("Citroen", "C3"),
    "Mercedes-Benz W123": ("Mercedes-Benz", "Classe E"),
    "Renault Symbioz": ("Renault", "Symbioz"),
    "Renault 5 E-Tech Electric": ("Renault", "5"),
    "Citroën C5 Aircross": ("Citroen", "C5 Aircross"),
    "Tesla Model Y": ("Tesla", "Model Y"),
    "Renault Austral": ("Renault", "Austral"),
    "Ford Puma": ("Ford", "Puma"),
    "Opel Mokka-e": ("Opel", "Mokka"),
    "Opel Grandland": ("Opel", "Grandland"),
    "Opel Grandland X": ("Opel", "Grandland"),
    "Renault Kangoo": ("Renault", "Kangoo"),
    "Renault Kangoo III": ("Renault", "Kangoo"),
    "Nissan Leaf": ("Nissan", "Leaf"),
    "Nissan Leaf (2019)": ("Nissan", "Leaf"),
    "Jaguar F-Pace": ("Jaguar", "F-Pace"),
    "Jaguar F-Pace (2)": ("Jaguar", "F-Pace"),
    "Aston Martin DB7 Vantage": ("Aston Martin", "DB7"),
    "Aston Martin DB12": ("Aston Martin", "DB12"),
    "Range Rover Sport SVR": ("Land Rover", "Range Rover Sport"),
    "Range Rover": ("Land Rover", "Range Rover"),
    "Morris Mini-Minor (1959)": ("Morris", "Mini-Minor"),
    "Mini John Cooper Works": ("Mini", "Cooper"),
    "Mini Cooper (1ere generation)": ("Mini", "Cooper"),
    "Cupra Formentor (restylee)": ("Cupra", "Formentor"),
    "Cupra Formentor": ("Cupra", "Formentor"),
    "Renault Twingo III (2)": ("Renault", "Twingo"),
    "Renault 4L (Mk2)": ("Renault", "4"),
    "Audi 100": ("Audi", "100"),
    "BYD Dolphin": ("BYD", "Dolphin"),
    "Kia Sportage": ("Kia", "Sportage"),
    "Renault Megane E-Tech": ("Renault", "Megane"),
    "Renault Espace V": ("Renault", "Espace"),
    "Renault Espace VI": ("Renault", "Espace"),
    "Renault Espace III": ("Renault", "Espace"),
    "Volkswagen Beetle": ("Volkswagen", "Coccinelle"),
    "Volkswagen Golf R": ("Volkswagen", "Golf"),
    "Volkswagen Tiguan": ("Volkswagen", "Tiguan"),
    "Ford Kuga": ("Ford", "Kuga"),
    "Toyota RAV4 (1994)": ("Toyota", "RAV4"),
    "Toyota RAV4 GR Sport": ("Toyota", "RAV4"),
    "Toyota RAV4 (2013)": ("Toyota", "RAV4"),
    "Toyota RAV4 Hybrid (2019)": ("Toyota", "RAV4"),
    "Fiat Multipla": ("Fiat", "Multipla"),
    "Lamborghini Gallardo": ("Lamborghini", "Gallardo"),
    "Lamborghini Urus": ("Lamborghini", "Urus"),
    "Bentley Continental GT": ("Bentley", "Continental GT"),
    "Rolls-Royce Silver Cloud III": ("Rolls-Royce", "Silver Cloud"),
    "Fiat Punto GT (1993)": ("Fiat", "Punto"),
    "Fiat 500X (2024)": ("Fiat", "500X"),
    "Fiat Topolino (2023)": ("Fiat", "Topolino"),
    "Citroen 2CV": ("Citroen", "2CV"),
    "Citroen DS": ("Citroen", "DS"),
    "Citroen e-Mehari (2016)": ("Citroen", "Mehari"),
    "Citroen Traction Avant 11B": ("Citroen", "Traction Avant"),
    "Citroen C4 Picasso": ("Citroen", "C4 Picasso"),
    "DS 4 E-Tense (2021)": ("DS", "DS4"),
    "Alpine A110 (1963)": ("Alpine", "A110"),
    "Alpine A110 Gendarmerie": ("Alpine", "A110"),
    "Tesla Cybertruck (2024)": ("Tesla", "Cybertruck"),
    "Peugeot 806": ("Peugeot", "806"),
    "Peugeot RCZ": ("Peugeot", "RCZ"),
    "Peugeot 3008 (2023)": ("Peugeot", "3008"),
    "Peugeot 5008 (2024)": ("Peugeot", "5008"),
    "Ford Focus (2016)": ("Ford", "Focus"),
    "Nissan Micra (2017)": ("Nissan", "Micra"),
    "Nissan Micra (2003)": ("Nissan", "Micra"),
    "Nissan Juke (2019)": ("Nissan", "Juke"),
    "Nissan Note (2009)": ("Nissan", "Note"),
    "Nissan Patrol (2019)": ("Nissan", "Patrol"),
    "MG ZS": ("MG", "ZS"),
    "MG 3 Hybrid (2024)": ("MG", "3"),
    "Volvo XC40": ("Volvo", "XC40"),
    "Volvo C30 (2008)": ("Volvo", "C30"),
    "Jaecoo 5 (2025)": ("Jaecoo", "5"),
    "Lancia Ypsilon (2010)": ("Lancia", "Ypsilon"),
    "Lancia Ypsilon (2025)": ("Lancia", "Ypsilon"),
    "Lexus CT 200h": ("Lexus", "CT"),
    "Lexus LBX (2024)": ("Lexus", "LBX"),
    "Porsche 911 Turbo S (992)": ("Porsche", "911"),
    "Porsche Macan Electrique (2024)": ("Porsche", "Macan"),
}

if __name__ == "__main__":
    import json, os
    BASE = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(BASE, "cars.json"), encoding="utf-8") as f:
        cars = json.load(f)
    missing = [c["name"] for c in cars if c["name"] not in BRAND_MODEL]
    print(f"{len(cars)} cars, {len(missing)} missing from map")
    for n in missing:
        print(" - MISSING:", n)
    brands = sorted(set(b for b, m in BRAND_MODEL.values()))
    print(f"\n{len(brands)} distinct brands:")
    print(", ".join(brands))
