#!/bin/bash
set -e
cd "$(dirname "$0")/../raw"

if [ ! -s peugeot-208-mk2.orig ]; then echo "Downloading Peugeot 208 (Mk2)..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o peugeot-208-mk2.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Peugeot%20208%20A%20Facelift%20(80915).jpg' || echo "FAILED: Peugeot 208 (Mk2)"; fi
if [ ! -s fiat-500l-cross.orig ]; then echo "Downloading Fiat 500L Cross..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o fiat-500l-cross.orig https://commons.wikimedia.org/wiki/Special:FilePath/2018%20Fiat%20500L%20Cross%20facelift%201.4%20Front.jpg || echo "FAILED: Fiat 500L Cross"; fi
if [ ! -s mazda-mx-5.orig ]; then echo "Downloading Mazda MX-5..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o mazda-mx-5.orig https://commons.wikimedia.org/wiki/Special:FilePath/2015%20Mazda%20MX-5%20ND%202.0%20SKYACTIV-G%20160%20i-ELOOP%20Rubinrot-Metallic%20LED-Scheinwerfer%20Front-Draufsicht.jpg || echo "FAILED: Mazda MX-5"; fi
if [ ! -s volvo-245.orig ]; then echo "Downloading Volvo 245..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o volvo-245.orig https://commons.wikimedia.org/wiki/Special:FilePath/Auto%20Volvo%20245%20Mayakovskogo%20street%20Mayakovskogo%20street%202025-01%20040.JPG || echo "FAILED: Volvo 245"; fi
if [ ! -s skoda-favorit.orig ]; then echo "Downloading Skoda Favorit..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o skoda-favorit.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/1991%20Skoda%20Favrorit%20Forum%20Plus%20(14587340313).jpg' || echo "FAILED: Skoda Favorit"; fi
if [ ! -s hyundai-veloster.orig ]; then echo "Downloading Hyundai Veloster..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o hyundai-veloster.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/%2712%20Hyundai%20Veloster%20(%2712%20MIAS).JPG' || echo "FAILED: Hyundai Veloster"; fi
if [ ! -s chevrolet-corvette.orig ]; then echo "Downloading Chevrolet Corvette..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o chevrolet-corvette.orig https://commons.wikimedia.org/wiki/Special:FilePath/Chevrelet%20Corvette%20Front.jpg || echo "FAILED: Chevrolet Corvette"; fi
if [ ! -s mini-classique.orig ]; then echo "Downloading Mini (classique)..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o mini-classique.orig https://commons.wikimedia.org/wiki/Special:FilePath/1992%20Mini%20Mark%20VI%201275cc%20at%20Hatfield%20Heath%20Festival%202017.jpg || echo "FAILED: Mini (classique)"; fi
if [ ! -s jeep-wrangler.orig ]; then echo "Downloading Jeep Wrangler..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o jeep-wrangler.orig https://commons.wikimedia.org/wiki/Special:FilePath/2017%20Jeep%20Wrangler%20Sahara%20in%20Granite%20Crystal%20Metallic,%20Front%20Right,%2007-29-2023.jpg || echo "FAILED: Jeep Wrangler"; fi
if [ ! -s kia-sorento.orig ]; then echo "Downloading Kia Sorento..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o kia-sorento.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/%2709%20Kia%20Sorento%20EX%20(MIAS).JPG' || echo "FAILED: Kia Sorento"; fi
if [ ! -s land-rover-defender.orig ]; then echo "Downloading Land Rover Defender..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o land-rover-defender.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Land%20Rover%20DEFENDER%20110%20X-DYNAMIC%20HSE%20(L663).jpg' || echo "FAILED: Land Rover Defender"; fi
if [ ! -s chevrolet-colorado.orig ]; then echo "Downloading Chevrolet Colorado..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o chevrolet-colorado.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/%2715%20Chevrolet%20Colorado%20(MIAS%20%2715).JPG' || echo "FAILED: Chevrolet Colorado"; fi
if [ ! -s jeep-grand-cherokee.orig ]; then echo "Downloading Jeep Grand Cherokee..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o jeep-grand-cherokee.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/%2712%20Jeep%20Grand%20Cherokee%20SRT-8%20(MIAS%20%2712).JPG' || echo "FAILED: Jeep Grand Cherokee"; fi
if [ ! -s renault-4.orig ]; then echo "Downloading Renault 4..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-4.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Deluxe%20Renault%204,%20with%20headlamp%20wipers,%20probably%20to%20get%20rid%20of%20mosquitos%20in%20the%20north%20(10759067994).jpg' || echo "FAILED: Renault 4"; fi
if [ ! -s renault-clio.orig ]; then echo "Downloading Renault Clio..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-clio.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Renault%20Clio%20(front%20quarter)%20red.JPG' || echo "FAILED: Renault Clio"; fi
if [ ! -s peugeot-208-gti.orig ]; then echo "Downloading Peugeot 208 GTi..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o peugeot-208-gti.orig https://commons.wikimedia.org/wiki/Special:FilePath/The%20frontview%20of%20Peugeot%20208%20GTi.JPG || echo "FAILED: Peugeot 208 GTi"; fi
if [ ! -s porsche-911.orig ]; then echo "Downloading Porsche 911..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o porsche-911.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/2013%20Porsche%20911%20Carrera%204S%20(991)%20(9626546987).jpg' || echo "FAILED: Porsche 911"; fi
if [ ! -s ford-mustang.orig ]; then echo "Downloading Ford Mustang..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o ford-mustang.orig https://commons.wikimedia.org/wiki/Special:FilePath/2015%20Ford%20Mustang%20Front%20View.jpg || echo "FAILED: Ford Mustang"; fi
if [ ! -s ford-mustang-1968.orig ]; then echo "Downloading Ford Mustang (1968)..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o ford-mustang-1968.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Ford%20Mustang%20GT,%201968%20(1).jpg' || echo "FAILED: Ford Mustang (1968)"; fi
if [ ! -s ford-edge.orig ]; then echo "Downloading Ford Edge..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o ford-edge.orig https://commons.wikimedia.org/wiki/Special:FilePath/2019%20Ford%20Edge%20ST,%20White%20Platinum,%206.24.19.jpg || echo "FAILED: Ford Edge"; fi
if [ ! -s citroen-c2.orig ]; then echo "Downloading Citroën C2..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o citroen-c2.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Citroen%20C2,%2040.%20ADAC%20Stormarn%20Rallye,%20Luetjensee%20(TR256803).jpg' || echo "FAILED: Citroën C2"; fi
if [ ! -s bmw-x6-m.orig ]; then echo "Downloading BMW X6 M..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o bmw-x6-m.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/%2715%20BMW%20X6%20M%20(MIAS%20%2715).jpg' || echo "FAILED: BMW X6 M"; fi
if [ ! -s bmw-323i-e21.orig ]; then echo "Downloading BMW 323i (E21)..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o bmw-323i-e21.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/BMW%20323i%20E21%20(6806823446).jpg' || echo "FAILED: BMW 323i (E21)"; fi
if [ ! -s nissan-ariya.orig ]; then echo "Downloading Nissan Ariya..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o nissan-ariya.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Nissan%20ARIYA%20B6%20limited%20(1).jpg' || echo "FAILED: Nissan Ariya"; fi
if [ ! -s fiat-500-1967.orig ]; then echo "Downloading Fiat 500 (1967)..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o fiat-500-1967.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Fiat%20500%20L%20(1967%E2%80%9371%20model).jpg' || echo "FAILED: Fiat 500 (1967)"; fi
if [ ! -s audi-a4.orig ]; then echo "Downloading Audi A4..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o audi-a4.orig https://commons.wikimedia.org/wiki/Special:FilePath/2015%20Audi%20A4%20B9%20S%20line%20Tangorot%20LED-Matrix-Scheinwerfer%20Detail.jpg || echo "FAILED: Audi A4"; fi
if [ ! -s fiat-punto.orig ]; then echo "Downloading Fiat Punto..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o fiat-punto.orig https://commons.wikimedia.org/wiki/Special:FilePath/%22%2012%20-%20ITALY%20-%20Fiat%20Punto%202012%2004.JPG || echo "FAILED: Fiat Punto"; fi
if [ ! -s honda-civic.orig ]; then echo "Downloading Honda Civic..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o honda-civic.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/2015%20Honda%20Civic%20Si%20Coupe%20(21027301342).jpg' || echo "FAILED: Honda Civic"; fi
if [ ! -s mercedes-benz-sl-r107.orig ]; then echo "Downloading Mercedes-Benz SL (R107)..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o mercedes-benz-sl-r107.orig https://commons.wikimedia.org/wiki/Special:FilePath/Mercedes-Benz%20SL%20R107%20-%20Flickr%20-%20exfordy.jpg || echo "FAILED: Mercedes-Benz SL (R107)"; fi
if [ ! -s alfa-romeo-giulia.orig ]; then echo "Downloading Alfa Romeo Giulia..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o alfa-romeo-giulia.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/%22%2015%20-%20ITALY%20-%20Alfa%20Romeo%20Giulia%20QV%20(pre%20series)%20at%20Museo%20Alfa%20Romeo%20Arese%20world%20premiere%2005.jpg' || echo "FAILED: Alfa Romeo Giulia"; fi
if [ ! -s bmw-320d-touring.orig ]; then echo "Downloading BMW 320d Touring..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o bmw-320d-touring.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/BMW%20320d%20%E2%80%94%20E46-3%20(Touring)%20%E2%80%94%20blue%20livery%20%E2%80%94%20parked%20%E2%80%94%20Munich,%20Germany%20%E2%80%94%202005.jpg' || echo "FAILED: BMW 320d Touring"; fi
if [ ! -s dacia-duster.orig ]; then echo "Downloading Dacia Duster..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o dacia-duster.orig https://commons.wikimedia.org/wiki/Special:FilePath/Dacia%20Duster%20III%20GIMS%202024%201X7A2016.jpg || echo "FAILED: Dacia Duster"; fi
if [ ! -s porsche-911-turbo-s.orig ]; then echo "Downloading Porsche 911 Turbo S..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o porsche-911-turbo-s.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Porsche%20911%20(991)%20Turbo%20S%20LED%20headlight.jpg' || echo "FAILED: Porsche 911 Turbo S"; fi
if [ ! -s toyota-rav4.orig ]; then echo "Downloading Toyota RAV4..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o toyota-rav4.orig https://commons.wikimedia.org/wiki/Special:FilePath/2016%20Toyota%20RAV4%20Hybrid%202.5%20VVT-i%20marlingrau-metallic%20Frontalansicht.jpg || echo "FAILED: Toyota RAV4"; fi
if [ ! -s fiat-panda.orig ]; then echo "Downloading Fiat Panda..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o fiat-panda.orig https://commons.wikimedia.org/wiki/Special:FilePath/%22%2012%20-%20ITALY%20-%20Fiat%20Panda%204x4%20Off-road%20drive%20-%20Motorshow%20di%20Bologna%20011.JPG || echo "FAILED: Fiat Panda"; fi
if [ ! -s bmw-2000-classique.orig ]; then echo "Downloading BMW 2000 (classique)..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o bmw-2000-classique.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/BMW%202000%20touring,%2018.%20ADAC%20Stormarn%20Classic,%20Luetjensee%20(P1045451).jpg' || echo "FAILED: BMW 2000 (classique)"; fi
if [ ! -s volkswagen-golf.orig ]; then echo "Downloading Volkswagen Golf..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o volkswagen-golf.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/2009%20Volkswagen%20Golf%20(5K%20MY10)%20118TSI%20Comfortline%205-door%20hatchback%20(2011-11-08)%2001.jpg' || echo "FAILED: Volkswagen Golf"; fi
if [ ! -s toyota-corolla.orig ]; then echo "Downloading Toyota Corolla..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o toyota-corolla.orig https://commons.wikimedia.org/wiki/Special:FilePath/2014%20Toyota%20Corolla%20LED%20Headlight.jpg || echo "FAILED: Toyota Corolla"; fi
if [ ! -s toyota-yaris.orig ]; then echo "Downloading Toyota Yaris..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o toyota-yaris.orig https://commons.wikimedia.org/wiki/Special:FilePath/2022%20Toyota%20Yaris%201.5%20GR%20Sport,%20IIMS%20Hybrid,%20Grand%20City,%20Central%20Surabaya.jpg || echo "FAILED: Toyota Yaris"; fi
if [ ! -s audi-tt.orig ]; then echo "Downloading Audi TT..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o audi-tt.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Audi%20TT%202014%20(13558536333).jpg' || echo "FAILED: Audi TT"; fi
if [ ! -s ford-ranger.orig ]; then echo "Downloading Ford Ranger..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o ford-ranger.orig https://commons.wikimedia.org/wiki/Special:FilePath/2023%20Ford%20Ranger%20Raptor%20Double-Cab%202.0L%20Bi-Turbo%204x4.jpg || echo "FAILED: Ford Ranger"; fi
if [ ! -s mercedes-benz-classe-e.orig ]; then echo "Downloading Mercedes-Benz Classe E..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o mercedes-benz-classe-e.orig https://commons.wikimedia.org/wiki/Special:FilePath/2014%20Mercedes-Benz%20E-Class%20LED%20Headlight.jpg || echo "FAILED: Mercedes-Benz Classe E"; fi
if [ ! -s volkswagen-phaeton.orig ]; then echo "Downloading Volkswagen Phaeton..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o volkswagen-phaeton.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/2003%20Volkswagen%20Phaeton%20VR,%20Techno-Classica%202025,%20Essen%20(P1045896).jpg' || echo "FAILED: Volkswagen Phaeton"; fi
if [ ! -s honda-hr-v.orig ]; then echo "Downloading Honda HR-V..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o honda-hr-v.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/2016%20Honda%20HR-V%20EX-L%20front%20(21028254132).jpg' || echo "FAILED: Honda HR-V"; fi
if [ ! -s alfa-romeo-giulia-quadrifoglio.orig ]; then echo "Downloading Alfa Romeo Giulia Quadrifoglio..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o alfa-romeo-giulia-quadrifoglio.orig https://commons.wikimedia.org/wiki/Special:FilePath/Carabinieri%20Alfa%20Romeo%20Giulia%20Quadrifoglio.jpg || echo "FAILED: Alfa Romeo Giulia Quadrifoglio"; fi
if [ ! -s fiat-500l.orig ]; then echo "Downloading Fiat 500L..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o fiat-500l.orig https://commons.wikimedia.org/wiki/Special:FilePath/%22%2013%20-%20Italian%20fashion%20SUV%20-%20Fiat%20500L%20Trekking%20front%20grey%20and%20green.jpg || echo "FAILED: Fiat 500L"; fi
if [ ! -s fiat-500e.orig ]; then echo "Downloading Fiat 500e..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o fiat-500e.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/%22%2015%20-%20EXPO%20MILANO%202015%20-%20Front%20view%20of%20500e%20(FIAT).jpg' || echo "FAILED: Fiat 500e"; fi
if [ ! -s ferrari-ff.orig ]; then echo "Downloading Ferrari FF..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o ferrari-ff.orig https://commons.wikimedia.org/wiki/Special:FilePath/%22%2012%20-%20ITALY%20-%20Ferrari%20FF%20a%20Bologna%2005.jpg || echo "FAILED: Ferrari FF"; fi
if [ ! -s toyota-land-cruiser.orig ]; then echo "Downloading Toyota Land Cruiser..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o toyota-land-cruiser.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/2024%20Toyota%20Land%20Cruiser%20(United%20States)%20front%20view.jpg' || echo "FAILED: Toyota Land Cruiser"; fi
if [ ! -s lexus-gs-f.orig ]; then echo "Downloading Lexus GS-F..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o lexus-gs-f.orig https://commons.wikimedia.org/wiki/Special:FilePath/2016%20Lexus%20GS-F%20Fujiweiss%20LED-Scheinwerfer.jpg || echo "FAILED: Lexus GS-F"; fi
if [ ! -s peugeot-2008-ii.orig ]; then echo "Downloading Peugeot 2008 II..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o peugeot-2008-ii.orig https://commons.wikimedia.org/wiki/Special:FilePath/2020%20Peugeot%202008%20Allure%20Front.jpg || echo "FAILED: Peugeot 2008 II"; fi
if [ ! -s opel-corsa.orig ]; then echo "Downloading Opel Corsa..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o opel-corsa.orig https://commons.wikimedia.org/wiki/Special:FilePath/Opel%20Corsa%20D%2020090912%20front.JPG || echo "FAILED: Opel Corsa"; fi
if [ ! -s renault-captur.orig ]; then echo "Downloading Renault Captur..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-captur.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/2017%20Renault%20Captur%20front%20tq%20(red%20phase%20II)%20crop.jpg' || echo "FAILED: Renault Captur"; fi
if [ ! -s citroen-c4-iii.orig ]; then echo "Downloading Citroën C4 III..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o citroen-c4-iii.orig https://commons.wikimedia.org/wiki/Special:FilePath/2021%20Citroen%20C4%20Shine%20Front.jpg || echo "FAILED: Citroën C4 III"; fi
if [ ! -s volkswagen-polo.orig ]; then echo "Downloading Volkswagen Polo..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o volkswagen-polo.orig https://commons.wikimedia.org/wiki/Special:FilePath/1986%20Volkswagen%20Polo%20C%20Formel%20E%201.3%20Front.jpg || echo "FAILED: Volkswagen Polo"; fi
if [ ! -s skoda-octavia.orig ]; then echo "Downloading Skoda Octavia..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o skoda-octavia.orig https://commons.wikimedia.org/wiki/Special:FilePath/2005%20Skoda%20Octavia%20VRS%201.8%20Front.jpg || echo "FAILED: Skoda Octavia"; fi
if [ ! -s renault-megane-iv.orig ]; then echo "Downloading Renault Mégane IV..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-megane-iv.orig https://commons.wikimedia.org/wiki/Special:FilePath/2017%20Renault%20Megane%20Dynamique%20NAV%20DCi%201.5.jpg || echo "FAILED: Renault Mégane IV"; fi
if [ ! -s peugeot-3008-ii.orig ]; then echo "Downloading Peugeot 3008 II..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o peugeot-3008-ii.orig https://commons.wikimedia.org/wiki/Special:FilePath/Peugeot3008II-av-byRundvald.jpg || echo "FAILED: Peugeot 3008 II"; fi
if [ ! -s peugeot-308-iii.orig ]; then echo "Downloading Peugeot 308 III..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o peugeot-308-iii.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/2021%20-%20Peugeot%20308%20III%20(C)%20Allure%20-%2001.jpg' || echo "FAILED: Peugeot 308 III"; fi
if [ ! -s seat-ibiza.orig ]; then echo "Downloading Seat Ibiza..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o seat-ibiza.orig https://commons.wikimedia.org/wiki/Special:FilePath/Seat%20Ibiza%206J%20Facelift%20front%2020140401.jpg || echo "FAILED: Seat Ibiza"; fi
if [ ! -s renault-twingo-iii.orig ]; then echo "Downloading Renault Twingo III..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-twingo-iii.orig https://commons.wikimedia.org/wiki/Special:FilePath/2016%20Renault%20Twingo%20III%20SCe%2070.jpg || echo "FAILED: Renault Twingo III"; fi
if [ ! -s dacia-sandero.orig ]; then echo "Downloading Dacia Sandero..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o dacia-sandero.orig https://commons.wikimedia.org/wiki/Special:FilePath/2019%20Dacia%20Sandero%20Stepway%20Techroad%20Front.jpg || echo "FAILED: Dacia Sandero"; fi
if [ ! -s nissan-qashqai.orig ]; then echo "Downloading Nissan Qashqai..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o nissan-qashqai.orig https://commons.wikimedia.org/wiki/Special:FilePath/Nissan%20Qashqai%2020090620%20front.JPG || echo "FAILED: Nissan Qashqai"; fi
if [ ! -s renault-megane.orig ]; then echo "Downloading Renault Mégane..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-megane.orig https://commons.wikimedia.org/wiki/Special:FilePath/Renault%20M%C3%A9gane%20III%2020090801%20front.JPG || echo "FAILED: Renault Mégane"; fi
if [ ! -s mercedes-benz-560-sel-w126.orig ]; then echo "Downloading Mercedes-Benz 560 SEL (W126)..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o mercedes-benz-560-sel-w126.orig https://commons.wikimedia.org/wiki/Special:FilePath/Picture%20of%20Mercedes%20Benz%20W126%20560%20SEL.jpg || echo "FAILED: Mercedes-Benz 560 SEL (W126)"; fi
if [ ! -s mercedes-benz-classe-c.orig ]; then echo "Downloading Mercedes-Benz Classe C..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o mercedes-benz-classe-c.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Mercedes-Benz%20C-Class,%2018.%20ADAC%20Stormarn%20Classic,%20Luetjensee%20(20250405-TR257069).jpg' || echo "FAILED: Mercedes-Benz Classe C"; fi
if [ ! -s citroen-c3-iii.orig ]; then echo "Downloading Citroën C3 III..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o citroen-c3-iii.orig https://commons.wikimedia.org/wiki/Special:FilePath/2017%20Citroen%20C3%201.2%20Feel.jpg || echo "FAILED: Citroën C3 III"; fi
if [ ! -s mercedes-benz-w123.orig ]; then echo "Downloading Mercedes-Benz W123..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o mercedes-benz-w123.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Mercedes-Benz%20W123%20Sedan%20(Orange%20Julep%20%2710).jpg' || echo "FAILED: Mercedes-Benz W123"; fi
if [ ! -s renault-symbioz.orig ]; then echo "Downloading Renault Symbioz..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-symbioz.orig https://commons.wikimedia.org/wiki/Special:FilePath/Renault%20Symbioz%20IMG%202251.jpg || echo "FAILED: Renault Symbioz"; fi
if [ ! -s renault-5-e-tech-electric.orig ]; then echo "Downloading Renault 5 E-Tech Electric..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-5-e-tech-electric.orig https://commons.wikimedia.org/wiki/Special:FilePath/White%20Renault%205%20E-Tech%20Electric%20-%202026-02-26.jpg || echo "FAILED: Renault 5 E-Tech Electric"; fi
if [ ! -s citroen-c5-aircross.orig ]; then echo "Downloading Citroën C5 Aircross..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o citroen-c5-aircross.orig 'https://commons.wikimedia.org/wiki/Special:FilePath/Citroen%20C5%20AIRCROSS%20SUV%20SHINE%20(3BA-C845G06)%20front.jpg' || echo "FAILED: Citroën C5 Aircross"; fi
if [ ! -s tesla-model-y.orig ]; then echo "Downloading Tesla Model Y..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o tesla-model-y.orig https://commons.wikimedia.org/wiki/Special:FilePath/2022%20Tesla%20Model%20Y%20Long%20Range%20AWD%20Front.jpg || echo "FAILED: Tesla Model Y"; fi
if [ ! -s renault-austral.orig ]; then echo "Downloading Renault Austral..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o renault-austral.orig https://commons.wikimedia.org/wiki/Special:FilePath/2023%20Renault%20Austral%201.2%20E-Tech%20Hybrid%20techno%20at%20Renault%20Manchester%2001.jpg || echo "FAILED: Renault Austral"; fi
if [ ! -s ford-puma.orig ]; then echo "Downloading Ford Puma..."; curl -sS -L --ssl-no-revoke -A "Mozilla/5.0" -o ford-puma.orig https://commons.wikimedia.org/wiki/Special:FilePath/2020%20Ford%20Puma%20Titanium%20EcoBoost%20Hybrid%201.0%20Front.jpg || echo "FAILED: Ford Puma"; fi
