# Modeles reels supplementaires par marque, utilises uniquement comme leurres dans la
# liste deroulante "Modele" du Mode Expert (aucune photo associee) -- pour garantir au
# moins 6 choix par marque meme quand le catalogue photo n'en couvre qu'un ou deux.
EXTRA_MODELS_BY_BRAND = {
    "Mazda": ["3", "6", "2", "CX-5", "RX-7"],
    "Hyundai": ["i30", "Tucson", "Kona", "Santa Fe", "Ioniq 5"],
    "Chevrolet": ["Camaro", "Silverado", "Malibu", "Cruze", "Spark"],
    "Alfa Romeo": ["Giulietta", "Stelvio", "4C", "156", "Spider"],
    "Ferrari": ["488", "F40", "Roma", "Portofino", "Testarossa"],
    "Seat": ["Leon", "Arona", "Ateca", "Tarraco", "Alhambra"],
    "Jaguar": ["XE", "XF", "F-Type", "E-Pace", "I-Pace"],
    "Morris": ["Marina", "Oxford", "Minor", "Ital", "1100"],
    "Cupra": ["Leon", "Ateca", "Born", "Tavascan", "Terramar"],
    "BYD": ["Atto 3", "Seal", "Han", "Tang", "Yuan"],
    "Bentley": ["Bentayga", "Flying Spur", "Mulsanne", "Arnage", "Azure"],
    "Rolls-Royce": ["Phantom", "Ghost", "Wraith", "Cullinan", "Corniche"],
    "DS": ["DS3", "DS3 Crossback", "DS5", "DS7", "DS9"],
    "Alpine": ["A290", "A106", "A108", "A310", "A610"],
    "Jaecoo": ["6", "7", "8", "J7", "J8"],
    "Lancia": ["Delta", "Fulvia", "Stratos", "Thema", "Musa"],
    "Skoda": ["Fabia", "Superb", "Kodiaq", "Kamiq"],
    "Mini": ["Clubman", "Countryman", "Paceman", "Coupe"],
    "Jeep": ["Renegade", "Compass", "Cherokee", "Gladiator"],
    "Kia": ["Picanto", "Ceed", "Niro", "Stonic"],
    "Porsche": ["Cayenne", "Panamera", "Taycan", "Boxster"],
    "Honda": ["Jazz", "CR-V", "Accord", "e:Ny1"],
    "Dacia": ["Spring", "Jogger", "Logan", "Bigster"],
    "Tesla": ["Model 3", "Model S", "Model X", "Roadster"],
    "Aston Martin": ["Vantage", "DBS", "DB11", "Vanquish"],
    "Lamborghini": ["Huracan", "Aventador", "Revuelto", "Diablo"],
    "MG": ["HS", "MG4", "Cyberster", "5"],
    "Volvo": ["XC60", "XC90", "S60"],
    "Land Rover": ["Discovery", "Range Rover Evoque", "Range Rover Velar"],
    "Audi": ["A3", "Q5", "e-tron"],
    "Lexus": ["RX", "NX", "IS"],
    "Opel": ["Astra", "Insignia", "Crossland"],
    "BMW": ["Serie 5", "X3"],
    "Mercedes-Benz": ["Classe A", "GLC"],
    "Toyota": ["Prius", "C-HR"],
    "Volkswagen": ["Passat"],
}
