# Batch 3 - initial name guesses (verifiees/corrigees visuellement apres telechargement
# dans integrate_new_cars_3.py avant compression).
NEW_CARS_3 = [
    {"wikiFile": "Alfa_Romeo_Tonale_1X7A0319.jpg", "name_guess": "Alfa Romeo Tonale"},
    {"wikiFile": "Alfa_Romeo_Junior_IMG_0462.jpg", "name_guess": "Alfa Romeo Junior"},
    {"wikiFile": "Alfa_Romeo_Junior_Auto_Zuerich_2024_DSC_6376.jpg", "name_guess": "Alfa Romeo Junior (2)"},
    {"wikiFile": "Audi_Q2_FL_1X7A0303.jpg", "name_guess": "Audi Q2"},
    {"wikiFile": "2023_Dacia_Spring_1X7A6282.jpg", "name_guess": "Dacia Spring"},
    {"wikiFile": "Citro%C3%ABn_%C3%AB-C5_Aircross_Auto_Zuerich_2025_DSC_3486.jpg", "name_guess": "Citroen e-C5 Aircross"},
    {"wikiFile": "2016_BMW_i8.jpg", "name_guess": "BMW i8"},
    {"wikiFile": "Ford_Explorer_EV_IMG_2120.jpg", "name_guess": "Ford Explorer EV"},
    {"wikiFile": "Ford_Capri_(2024)_Autofr%C3%BChling_Ulm_2025_DSC_8745.jpg", "name_guess": "Ford Capri (2024)"},
    {"wikiFile": "Hyundai_Inster_DSC_7945.jpg", "name_guess": "Hyundai Inster"},
    {"wikiFile": "Suzuki_Jimny_on_the_parking_near_%C3%9Eorbj%C3%B6rn_Mountain,_Iceland,_20230430_1630_3697.jpg", "name_guess": "Suzuki Jimny"},
    {"wikiFile": "Hyundai_Kona_(SX2)_1X7A1647.jpg", "name_guess": "Hyundai Kona"},
    {"wikiFile": "Hyundai_Ioniq_6_1X7A7083.jpg", "name_guess": "Hyundai Ioniq 6"},
    {"wikiFile": "2019_Jeep_Renegade_1.6_Multijet.jpg", "name_guess": "Jeep Renegade"},
    {"wikiFile": "Jeep_Avenger_IMG_7815.jpg", "name_guess": "Jeep Avenger"},
    {"wikiFile": "Range_Rover_Evoque_(L551)_1X7A7459.jpg", "name_guess": "Range Rover Evoque"},
    {"wikiFile": "Mini_Countryman_(U25)_IMG_9521.jpg", "name_guess": "Mini Countryman"},
    {"wikiFile": "Peugeot_308_C_1X7A7329.jpg", "name_guess": "Peugeot 308"},
    {"wikiFile": "Skoda_Fabia_IV_1X7A0388.jpg", "name_guess": "Skoda Fabia"},
    {"wikiFile": "Paris_Motor_Show_2018,_Paris_(1Y7A2062).jpg", "name_guess": "A identifier (Paris Motor Show)"},
    {"wikiFile": "2019_SEAT_Arona_XCELLENCE_Lux_1.6.jpg", "name_guess": "Seat Arona"},
    {"wikiFile": "Toyota_GR86_SZ.jpg", "name_guess": "Toyota GR86"},
    {"wikiFile": "Volkswagen_T-Cross_1X7A0366.jpg", "name_guess": "Volkswagen T-Cross"},
    {"wikiFile": "Volkswagen_T-Cross_1X7A0363.jpg", "name_guess": "Volkswagen T-Cross (2)"},
    {"wikiFile": "Volkswagen_T-Roc_(2021)_1X7A0330.jpg", "name_guess": "Volkswagen T-Roc (2021)"},
    {"wikiFile": "Volkswagen_ID.5_GTX_1X7A0318.jpg", "name_guess": "Volkswagen ID.5 GTX"},
    {"wikiFile": "Smart_Hashtag_3_DSC_7992.jpg", "name_guess": "Smart #3"},
]
